version: '3'

services:
  nestapp:
    container_name: nest-backend
    image: nestjs
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - backend_bridge
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - backend_bridge
    volumes:
      - redis:/data

  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - backend_bridge
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - .env
    networks:
      - backend_bridge
    ports:
      - '5050:80'
    depends_on:
      - postgres

networks:
  backend_bridge:
    driver: bridge

volumes:
  pgdata: {}
  redis:
    driver: local
