version: '3'

services:
  nestapp:
    container_name: fyp-nest
    image: syed007hassan/fyp-nest:latest
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - backend_bridge
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis

  redis:
    container_name: fyp-redis
    image: syed007hassan/fyp-redis:latest
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - backend_bridge
    volumes:
      - redis:/data

  postgres:
    container_name: fyp-postgres
    image: syed007hassan/fyp-postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - backend_bridge
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: fyp-pgadmin
    image: syed007hassan/fyp-pgadmin4:latest
    env_file:
      - .env
    networks:
      - backend_bridge
    ports:
      - '5050:80'
    depends_on:
      - postgres

networks:
  backend_bridge:
    driver: bridge

volumes:
  pgdata: {}
  redis:
    driver: local
